[pytest]
pythonpath = .
# Exclude web3 pytest plugin to avoid eth-typing conflicts
addopts = -p no:pytest_ethereum
filterwarnings =
    ignore::DeprecationWarning:web3
    ignore::DeprecationWarning:websockets
    ignore::PendingDeprecationWarning:starlette

