"""Add legal compliance tables

Revision ID: 91df3944a664
Revises: 
Create Date: 2025-10-29 20:30:48.038016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '91df3944a664'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuit_breaker_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('rule_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('action_taken', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('auto_triggered', sa.Boolean(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sqlmodel.sql.sqltypes.AutoString(length=42), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circuit_breaker_events_created_at'), 'circuit_breaker_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_circuit_breaker_events_event_type'), 'circuit_breaker_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_circuit_breaker_events_resolved'), 'circuit_breaker_events', ['resolved'], unique=False)
    op.create_table('geo_restrictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('country_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('wallet_address', sqlmodel.sql.sqltypes.AutoString(length=42), nullable=True),
    sa.Column('blocked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_restrictions_blocked_at'), 'geo_restrictions', ['blocked_at'], unique=False)
    op.create_index(op.f('ix_geo_restrictions_country_code'), 'geo_restrictions', ['country_code'], unique=False)
    op.create_index(op.f('ix_geo_restrictions_ip_address'), 'geo_restrictions', ['ip_address'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('wallet_address', sqlmodel.sql.sqltypes.AutoString(length=42), nullable=True),
    sa.Column('action_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('resource_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_wallet_address'), 'audit_logs', ['wallet_address'], unique=False)
    op.create_table('terms_acceptances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('wallet_address', sqlmodel.sql.sqltypes.AutoString(length=42), nullable=False),
    sa.Column('terms_version', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('privacy_version', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('age_verified', sa.Boolean(), nullable=False),
    sa.Column('birthdate', sa.DateTime(), nullable=True),
    sa.Column('terms_accepted', sa.Boolean(), nullable=False),
    sa.Column('privacy_accepted', sa.Boolean(), nullable=False),
    sa.Column('risk_accepted', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terms_acceptances_wallet_address'), 'terms_acceptances', ['wallet_address'], unique=False)
    op.create_index(op.f('ix_transactionlog_tx_hash'), 'transactionlog', ['tx_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactionlog_tx_hash'), table_name='transactionlog')
    op.drop_index(op.f('ix_terms_acceptances_wallet_address'), table_name='terms_acceptances')
    op.drop_table('terms_acceptances')
    op.drop_index(op.f('ix_audit_logs_wallet_address'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_geo_restrictions_ip_address'), table_name='geo_restrictions')
    op.drop_index(op.f('ix_geo_restrictions_country_code'), table_name='geo_restrictions')
    op.drop_index(op.f('ix_geo_restrictions_blocked_at'), table_name='geo_restrictions')
    op.drop_table('geo_restrictions')
    op.drop_index(op.f('ix_circuit_breaker_events_resolved'), table_name='circuit_breaker_events')
    op.drop_index(op.f('ix_circuit_breaker_events_event_type'), table_name='circuit_breaker_events')
    op.drop_index(op.f('ix_circuit_breaker_events_created_at'), table_name='circuit_breaker_events')
    op.drop_table('circuit_breaker_events')
    # ### end Alembic commands ###
